### ISSUE TITLE
Vector too long

### ISSUE THREAD

**Issue by Ohmar999** [c22dev/TrollBox#23]
When trying to sideload through AltStore sideload fails because "![image](https://user-images.githubusercontent.com/64495802/216832709-c76ea1f1-e95a-404c-80b0-172ea094c021.png)vector too long"

**Comment by c22dev** [comment]
Windows Defender does need to be off as already
mentioned. However, Windows Real Time Protection has to be off as well
Open Windows Security/Defender click virus & threat protection under virus & threat protection settings, click the blue text "Manage Settings". The first slider should be Real Time Protection. Turn it off. This is because windows detect the exploit as a virus.

**Comment by Ohmar999** [comment]
Yes this worked thank you!
